import { ArrowLeft, Minus, Plus, Trash2 } from "lucide-react";
import { Link } from "wouter";
import { toast } from "sonner";
import { StorefrontLayout } from "@/components/StorefrontLayout";
import { pkr } from "@/components/ProductCard";
import { trpc } from "@/lib/trpc";

export default function Cart() {
  const utils = trpc.useUtils();
  const cart = trpc.cart.get.useQuery();
  const update = trpc.cart.updateQuantity.useMutation({ onSuccess: () => utils.cart.get.invalidate(), onError: error => toast.error(error.message) });
  if (cart.isLoading) return <StorefrontLayout><div className="site-container cart-page cart-page--loading"><div className="skeleton-line skeleton-line--short" /><div className="skeleton-line skeleton-line--title" /><div className="cart-layout" style={{ marginTop: 30 }}><div className="cart-skeleton"><div /><span /><span /></div><div className="summary-card"><div className="skeleton-line" style={{ height: 24, width: "45%" }} /><div className="skeleton-line" style={{ height: 16, marginTop: 24 }} /><div className="skeleton-line" style={{ height: 16, marginTop: 16 }} /></div></div></div></StorefrontLayout>;
  if (!cart.data?.items.length) return <StorefrontLayout><div className="site-container cart-page"><h1 className="display catalog-title">Your bag</h1><div className="empty-state" style={{ marginTop: 28 }}>Your bag is waiting for a pair with a story. <Link className="button-text" href="/shop">Explore the collection</Link></div></div></StorefrontLayout>;
  return <StorefrontLayout><div className="site-container cart-page"><div className="breadcrumb"><Link href="/shop">Shop</Link> / Your bag</div><div className="checkout-progress" aria-label="Checkout progress"><span className="checkout-progress__active">1. Bag</span><i /><span>2. Delivery</span><i /><span>3. Confirmation</span></div><h1 className="display catalog-title">Your bag</h1><div className="cart-layout" style={{ marginTop: 30 }}><div>{cart.data.items.map(row => <article className="cart-item" key={row.item.id}>{row.image ? <img loading="lazy" className="cart-item__image" src={row.image} alt={row.product.name} /> : <div className="cart-item__image product-card__image--empty">Image</div>}<div><h3>{row.product.name}</h3><p>{row.variant.color} · Size {row.variant.size}</p>{row.available < row.item.quantity && <span className="stock-empty cart-stock-warning">Only {row.available} currently available</span>}<p style={{ marginTop: 10, fontWeight: 700, color: "var(--ink)" }}>{pkr(row.finalPrice)} {row.finalPrice < row.regularPrice && <span className="price-old">{pkr(row.regularPrice)}</span>}</p></div><div><div className="quantity-stepper"><button disabled={update.isPending || row.item.quantity <= 1} onClick={() => update.mutate({ itemId: row.item.id, quantity: row.item.quantity - 1 })} aria-label="Decrease quantity"><Minus size={14} /></button><span>{row.item.quantity}</span><button disabled={update.isPending || row.item.quantity >= row.available} onClick={() => update.mutate({ itemId: row.item.id, quantity: row.item.quantity + 1 })} aria-label="Increase quantity"><Plus size={14} /></button></div><button className="button-text" style={{ marginTop: 13, color: "var(--clay)" }} disabled={update.isPending} onClick={() => update.mutate({ itemId: row.item.id, quantity: 0 })}><Trash2 size={14} /> Remove</button></div></article>)}<Link className="button-text" href="/shop"><ArrowLeft size={15} /> Continue shopping</Link></div><aside className="summary-card cart-summary"><h3>Order summary</h3><div className="summary-row"><span>Subtotal</span><span>{pkr(cart.data.subtotal)}</span></div><div className="summary-row"><span>Product savings</span><span className="price-sale">− {pkr(cart.data.savings)}</span></div><div className="summary-row"><span>Delivery</span><span>Calculated at checkout</span></div><div className="summary-row summary-row--total"><span>Estimated total</span><span>{pkr(cart.data.subtotal)}</span></div><Link className="button-primary" href="/checkout">Secure checkout</Link><p style={{ margin: "14px 0 0", color: "var(--muted)", fontSize: 11, lineHeight: 1.5 }}>Price and stock are revalidated before your order is placed.</p></aside></div></div></StorefrontLayout>;
}
